version: '3.3'

services:
  web:
    image: coffeemate/nodejs
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/r-e-m-c
    working_dir: /var/www/r-e-m-c
    command: yarn start
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongodb:/data/db
